services:
  manager:
    image: ghcr.io/harikrishna2005/bot-launcher:latest
    container_name: bot_launcher_manager
    # Start the FastAPI server
    #command: ["uvicorn", "src.manager.app:app", "--host", "0.0.0.0"]
    command: ["poetry", "run", "run-manager"]
    ports:
      - "9501:9501"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always