services:
  manager:
    image: ghcr.io/harikrishna2005/bot-launcher:develop
    pull_policy: always
    container_name: bot_launcher_manager
    networks:
      - my_home_network
    ports:
      - "9501:9501"
    command: ["run-manager"]

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
networks:
  my_home_network:
    external: true